export const ADD_DATA = 'ADD_DATA';
export const RESET_DATA = 'RESET_DATA';

export enum EActionTypes {
  RECEIVE_SPOTIFY_TOKEN = 'RECEIVE_SPOTIFY_TOKEN',
  RECEIVE_SPOTIFY_DATA = 'RECEIVE_SPOTIFY_DATA',
  SPOTIFY_LOGIN = 'SPOTIFY_LOGIN',
}
